cluster-configs:
    secrets:
        db:
            mongo-db-username: ENC[AES256_GCM,data:amqve/McibhHrw==,iv:SO2QXhgW0v32PyM/C3gdtv2ves9w84v8ceiEzj6ySlY=,tag:STIKSkfF73vaky4MlQmO3Q==,type:str]
            mongo-db-password: ENC[AES256_GCM,data:iMJLyx/bHR/cmQ==,iv:0kV64fDCxGseiLuyJBXysh2NwYk020m9bD77lCLYxYM=,tag:o6P2yE5WGAxuTwRpga55Ig==,type:str]
            mongo-db-authenticated-uri: ENC[AES256_GCM,data:IVUFczZYynUvWs+awQ/HZAHbnpTcqoaDSSdN6ZVrnIT0P1rh8yvfpvRQvIUz761ZBhluz17Ie7XuEbx4Rg8fDGqQXPXX2HMyK5NJJFr3MEtGZhcyUxWnc3au9yWR4G+VG7DzIKhrD8p4ebK4YPShX/4Nnsg=,iv:wnQx4UV7Fwbe/DI2PFGpZg0j/ArJGUTs3zCT2a67VWE=,tag:UWfiJHwnemh1kOJGuVp7UQ==,type:str]
            username: ENC[AES256_GCM,data:ATlRW5+6taBL3y8=,iv:cfJqGqCdgVOe/v/abRFxU0+eQJ5vSl9qVfMah1lwvow=,tag:eEyOMMQJaXtUZTfBe7Ifyg==,type:str]
            password: ENC[AES256_GCM,data:kts77WIyqJz8qZk=,iv:ZTVm8toe924U5O65GtR5vzIp8fbdYP8Yp2Ghg/rdtx0=,tag:97k7GiUqDAxN8mBZBSr+lw==,type:str]
            pg-username: ENC[AES256_GCM,data:Jtpk+K3a7jjlJ4EqIqvy,iv:iZMjw58d/Ow9iAuOqokMcGc+mWl9hE1slbYt1Mcl2qk=,tag:oih9nK+M09G/K5A/C8ZCpA==,type:str]
            pg-password: ENC[AES256_GCM,data:bt70mzLQYbH0Z/Ov/aXR,iv:U2665qj0XZVpzRb9ifELgYzhJW1zaXzRNpP23uCUxIU=,tag:ZYwYkc0+p3Ej4IvvhAWhdw==,type:str]
            flywayUsername: ENC[AES256_GCM,data:jgDBSoNMX/IEc00=,iv:y/Z4wXBEon3Qn5BGWFImfyBc9o4fRHmyIy7M1RppFJ8=,tag:cro0vSc8ylcUAsIbSkhMAQ==,type:str]
            flywayPassword: ENC[AES256_GCM,data:zLg9HtL+Trwcl4g=,iv:AS1SnZfUBX6CmgLhIkcw3V+pZV346ZV2JrTiOW/du1Y=,tag:ONy4rZ0d2tXqiHYugE/EaQ==,type:str]
            druid_username: ENC[AES256_GCM,data:ni66W9i055G+1jE=,iv:bSK26I4Qeb+CI/obd371kMDF7k8+WIVziqvNFoKCz7w=,tag:o4HQ7wzgnlEQQIgCy5EbWw==,type:str]
            druid_password: ENC[AES256_GCM,data:jVzN9lBSWdSMT1Q=,iv:sOPruZ9R/3MULr16WiRfViL48xw+tYnl5VvHnijcp+8=,tag:qQFpHQjA3QzGWKVu+Kryaw==,type:str]
            druid_connect_uri: ENC[AES256_GCM,data:0OVx/7sJTANy7M9Ot+gBWdsddb/leEk59Ts0+2br22bOeIEpw/X9S0y0b2NTV6F2nMGWZ6GRGLBnGm5wtqgyjcNxkI+h3b1QqGKtqbOtOq3D3ijbvNXCcQTJkQ==,iv:LFQJJy73OUEVEjBRswtPqNgS8hnezr1F85zkxuECFGo=,tag:FpNNSxNeXDQBBbiAGiubow==,type:str]
            metabase_connect_uri: ENC[AES256_GCM,data:YKOBnJEpdzVloDsxiY4GYEnyPN0lfudYuwOxEFE8EcPRnQzNp296Egq4T/qBbaUUPDXI4xvnpheL4scfS7zM/e2NqygQJtZ5vBUomDBY9rLyhTBRxts/YhoYGUANO1eWFqgFatcS,iv:acWmNg6wi8S7Ka01kKKc/Ajd4sPswPQHDGWcq+GOYSg=,tag:kk3fDheH2ddvzLthvGjI0A==,type:str]
            druid_s3_accessKey: ENC[AES256_GCM,data:mGKJH44Y1prX7vM8Pr6FZwOe1Es=,iv:mwYC7A6Hj8Cep7L8sM2OjJiOMwSKo0jUMt6dQeDV96k=,tag:4GblJqduki+0fkT0u6eEvA==,type:str]
            druid_s3_secretKey: ENC[AES256_GCM,data:TSehwy3fjReOOVN0UUmW4SD2bl2pRwrx9egcLPBocy+AKTwrkTgsYQ==,iv:S5A6G6K0PYmIyU6ltUglxHSlEDOYgilqdJK9cPCK3sU=,tag:gyQrb281pckYOgRwyHwy5g==,type:str]
            keycloak-username: ENC[AES256_GCM,data:sNvoKHU=,iv:WNxag+0FypQv263k0DyukCxI9HVgRSjDwtb4XqbuRdE=,tag:RQ7BAYLTTSHyH96mNDy7/Q==,type:str]
            keycloak-password: ENC[AES256_GCM,data:5k+EdW+H9ShMI9n4pAA=,iv:olpK4IluRm3maFVE4w7+4GQTzX2LwoqYkI977rtwHAk=,tag:FM9Lp3SY8lbTauqsFo+Ylg==,type:str]
        keycloak-client-secrets:
            pspcl-keycloak-client-secret: ENC[AES256_GCM,data:mAL8fGsp0BowSi2Y9a0Y/Oez3MyOe/sO4AjHWJsokZqwmaGV,iv:GfRAg09T4VhxgY0aqKN/oqpJwC7PKyNpO70pxRD3RsU=,tag:Lpx2LCJhfvtqTn22rXjMiQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:434036464328:key/2c94f2aa-a4a2-4c2e-9360-385e126d4b0c
          created_at: "2021-11-19T10:33:33Z"
          enc: AQICAHi4WY6M7pgB9kt1kp2GVWk7xEwjeYZytfl2nCXfbia9/QH5L0HkyQc1UG9iC9Sqau2uAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKCusgjGxNcLYj+wzAgEQgDtr/hOBAC+G+Y0WeRz847/o5WMLQM33KOVAmvDx559ySXTgxp6Ry4GAVtpQJJBZJUVVchlTnntPtsUL+g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-22T06:55:53Z"
    mac: ENC[AES256_GCM,data:p+ngn/e+BhgGmc8VAihtXXAzS4UBjrPyw2fuHU6yFBBFyallFVV/uYkvpAHUoWXnYcurdFeW35ggn/Fr02Ag4Im4gROBPd0leREN0V4Pz2Y984E33N3KbUbJm+JS294IXhczedFb57mpGnlLs6PoO7kbrDbGHE4xWk4rHoaIhDo=,iv:J37ifZ1mDSDyX8/uzTcc1pAvNH7250IEwYCoXpuu4cc=,tag:uw6bJBBNfIWGXXxRoJbKoQ==,type:str]
    pgp:
        - created_at: "2021-11-19T10:33:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+gtFIQvidpKAQf+ITU7Zbnsme48ZOBgs/Vr3YRtLZlumjGl0tAYO8T1um2B
            wmyj7PrbCbudoBqnatX3YMCm/ozmc4cwGTImnLOWkDi5xQn/vpSYblXd6JW/V3d3
            W9h3xwbIglalMpXed33xWBNn0M1SCQXz3g2oln4mwrPCJayzgUiO0vqR3IZQehdm
            apC0F0Hha9Cut1eDybv0Lwo8mECyMvWVIlo9fmANmwjwe3kjWt8id2ZPo9ZSbvTL
            eo8owB603eat3uqR/rjteYTfJ8SoLts2j/jAHg0C3DyNjqDc5LQnIHXrvRNAvy7R
            LlJSHxjHLsGmFsJK/G+jt1CULScBI8KDc/dP5jvLS9JeAcYXsq3mSqL8nKUuaXd1
            ZGIEJSKvtqPBZwwp6OK2k+H1ebkZpsn3scRhybFTb+ug+TNNlAnLYmFXGwmURGGc
            2kz42wu6zPufTpSw7H3pA77ivJm0xhTvY9KnW8QN5g==
            =64p9
            -----END PGP MESSAGE-----
          fp: B9FF61E01273EDF7DE298B52F4D6BD77E5C66196
    unencrypted_suffix: _unencrypted
    version: 3.7.3
