
{{- with index .Values "cluster-configs" "secrets" "keycloak-client-secrets"  }}
{{- if index . "pspcl-keycloak-client-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:  
  pspcl-keycloak-client-secret: {{ index . "pspcl-keycloak-client-secret" | b64enc | quote }}
{{- end }}
{{- end }}