# Common Labels
labels:
  app: "dailyevening-read-cronjob"
  group: "mdms-read-cronjob"

cron:
  schedule: "0 18 * * *"

# Container Configs
image:
  repository: "api-cronjob"
  tag: "v1"

command: 
  - "python3"
  - "cronJobAPIConfig.py"
args: 
  - "dailyevening"

# Additional Container Envs
env: |
  - name: JOB_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name                    
resources: |
  requests: {}
  
    
